# Generated by Django 5.2.6 on 2026-02-13 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
