# Generated by Django 5.2.6 on 2026-02-13 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0002_alter_category_options_remove_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
