# Generated by Django 5.2.6 on 2026-02-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0003_remove_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Наш проект',
                'verbose_name_plural': 'Наши проекты',
                'db_table': 'our_projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
