# Generated by Django 5.2.6 on 2026-02-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0004_ourproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(unique=True, verbose_name='Номер шага')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='work_steps/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Шаг работы',
                'verbose_name_plural': 'Шаги работы',
                'db_table': 'work_steps',
                'ordering': ['step_number'],
            },
        ),
    ]
