# Generated by Django 5.2.6 on 2026-02-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0005_workstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('youtube_url', models.URLField(verbose_name='Ссылка YouTube')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='youtube_thumbnails/', verbose_name='Обложка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'YouTube видео',
                'verbose_name_plural': 'YouTube видео',
                'db_table': 'youtube_videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
