# Generated by Django 5.2.6 on 2026-02-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0006_youtubevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'verbose_name': 'Главная категория', 'verbose_name_plural': '01. Главные категории'},
        ),
        migrations.AlterModelOptions(
            name='ourproject',
            options={'ordering': ['-created_at'], 'verbose_name': 'Наш проект', 'verbose_name_plural': '03. Наши проекты'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': '02. Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='workstep',
            options={'ordering': ['step_number'], 'verbose_name': 'Шаг работы', 'verbose_name_plural': '04. Шаги работы'},
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='viewers',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
