# Generated by Django 5.2.6 on 2026-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0007_alter_maincategory_options_alter_ourproject_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Почему выбирают нас',
                'db_table': 'why_choose_us',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
