# Generated by Django 5.2.6 on 2026-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0008_whychooseus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('comment', models.TextField(verbose_name='Отзыв')),
                ('rating', models.IntegerField(default=5, help_text='От 1 до 5 звезд', verbose_name='Рейтинг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'db_table': 'client_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
