# Generated by Django 5.2.6 on 2026-02-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_config', '0009_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка на звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
                'db_table': 'callback_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='clientreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв клиента', 'verbose_name_plural': '07. Отзывы клиентов'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'Преимущество', 'verbose_name_plural': '06. Почему выбирают нас'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'YouTube видео', 'verbose_name_plural': '05. YouTube видео'},
        ),
    ]
